### ISSUE TITLE
Fix Unicode Character Rendering Quotes

### ISSUE THREAD

**Issue by Brahmanathaswami** [Brahmanathaswami/gurudeva.app#1]
This was working before in 2015. I thinks the code change from then to know to now, So we have to check Jacqueline handler when you open the quote. Perhaps it may need to "massage" the original data.

There is not in a dBase, the quote are in a text file

/data/gurudeva-quote.txt

**Comment by Brahmanathaswami** [comment]
@soapdog did you get this notification that I assigned to you?

**Comment by soapdog** [comment]
yes I did. Working  on it.

![gurudeva 2 _ 2019-03-05 10 51 31](https://user-images.githubusercontent.com/23247/53800474-ba6bff80-3f34-11e9-9d61-4f0a26899414.png)

**Comment by soapdog** [comment]
![stack _c__users_andre_kauai_gurudeva app_behavior_behavior_gurudevaapp livecodescript_ - code editor editing 2019-03-05 10 59 16](https://user-images.githubusercontent.com/23247/53800914-c3110580-3f35-11e9-8c0c-71ef6d35a5dd.png)

Unicode gremlins are not coming from the quotes but from the source code itself. Fixing them to normal quotes.

**Comment by soapdog** [comment]
![gurudeva 2 _ 2019-03-05 11 02 06](https://user-images.githubusercontent.com/23247/53801085-2438d900-3f36-11e9-9012-242b5909a391.png)

fixed.
