### ISSUE TITLE
Fix the  fullscreenmode to ShowAll 

### ISSUE THREAD

**Issue by Brahmanathaswami** [Brahmanathaswami/gurudeva.app#2]
for some reason the

 set the fullscreenmode of this stack to "showAll"

Is not working. Something has changed since 2015

**Comment by Brahmanathaswami** [comment]
you can make the stack responsive, removed the line 

set the fullsceenmode to "showAll" and see it is is easy or not.

**Comment by soapdog** [comment]
multiple errors happening just by opening the stack. Code inside the stack is quite broken.

![stack _c__users_andre_kauai_gurudeva app_behavior_behavior_gurudevaapp livecodescript_ - code editor editing 2019-03-05 10 41 46](https://user-images.githubusercontent.com/23247/53799875-6280c900-3f33-11e9-9717-a0bb84507616.png)

**Comment by soapdog** [comment]
I think that my fix for #1 might have fixed this. The error due to those unicode chars would prevent openstack from working and maybe the stack from resizing. I will try on my device next.

**Comment by soapdog** [comment]
There are a ton of errors happening on the app, mostly due to missing handlers which are all in the behavior which is probably not attached.

**Comment by soapdog** [comment]
![alacritty 2019-03-05 13 40 18](https://user-images.githubusercontent.com/23247/53809583-f4e19680-3f4c-11e9-899f-764b7df455f1.png)

All those _573_ errors are _Handler missing_ errors which probably means that the behavior is not attaching correctly.

**Comment by soapdog** [comment]
![win_20190305_14_01_44_pro](https://user-images.githubusercontent.com/23247/53810642-50ad1f00-3f4f-11e9-86fd-cda4bd17229d.jpg)

App is working now.
